/*
  [3] 
  [3] - AGORA VAMOS CRIAR A ESTRUTURA DE PASTAS 
        CRIE A PASTA SERVICES E DENTRO DELA CRIE A PASTA AUTOR E DENTRO DA PASTA
        CRIE A CLASSE AUTORSERVICE E A INTERFACE AUTORINTERFACE
 
  [3] - VA EM AUTORSERVICE E REFERENCIE A INTERFACE AUTORINTERFACE POR HERANÇA 
        A CLASSE AUTORSERVICE

  [3] - VÁ EM PROGRAM.CS  E ADICIONE O CODIGO QUE VAI REFERENCIAR QUE IAUTORINTERFACE
        ESTA IMPLEMENTADA EM AUTORSERVICE

   RESUMINDO CRIAMOS AS PASTAS SERVICE>AUTOR > ADICIONA EM AUTOR A CLASSE E A INTERFACE >
   LINKAMOS EM PROGRAM.CS A INTERFACE E A CLASSE

  [3] - AGORA VAMOS CRIAR NOSSA MODEL DE RESPOSTA NELA TERA O PADRÃO DE RESPOSTA
        SERA CRIADO EM MODEL > RESPONSEMODEL
   
  
  [4]
  [4] AGORA VAMOS DE FATO CRIAR O CONTROLLERS VA NA PASTA CONTROLLERS E CRIE UM CONTROLLER VAZIO 
      CHAMADO AUTORCONTROLLER VC SÓ VAI CRIAR APENAS E VOLTAR PARA IAUTORINTERFACE

  [4] EM IAUTORINTERFACE AGORA VAMOS FAZER OS METODOS QUE SERÃO A BASE DAS REQUISIÇÕES

  [4] DEPOIS DE CRIAR NOSSOS MÉTODOS NA IAUTORINTERFACE VAMOS EM AUTORSERVICE E IMPLEMENTAR OS MÉTODOS
      CRIADOS NA INTERFACE NESTE SERVICE

      [IMPORTANTE]
      OU SEJA VC CRIE OS METODOS COM SUA TIPAGEM NA INTERFACE E DEPOIS VC IMPLEMENTA ESTES METODOS
      NO SERVICE, É NO SERVICE QUE ESSES MÉTODOS TERÃO A SUA LOGICA FEITA
 
     NESTE MOMENTO DENTRO DO SERVICE FOI ADICIONANDO O CONTEXT DO BANCO E TAMBÉM O PROFESSOR ADICIONOU 
     ALGUNS DADOS MANUALMENTE NA TABELA LA NO SQL SERVER

  [4] FEZ TODA A LOGICA DOS METODOS DO SERVICE ENTÃO VA EM AUTORCONTROLLER
 
 
 
 
 
 
 
 
 
 
 
 */
